if (utils.scm_checkout()) return

// Create a Groovy Map that conforms to Artifactory's upload schema:
//     https://www.jfrog.com/confluence/display/RTF/Using+File+Specs#UsingFileSpecs-UploadSpecSchema
def ingest = [
    "files": [
        ["pattern": "test_results/**",
         "target": "generic-local/testbed/static/"],
    ],
]

// Create a new data configuration
dc0 = new DataConfig()

// Which Artifactory instance should be used?
// "bytesalad" is the identifaction string used for our Artifactory instance
dc0.server_id = "bytesalad"

// Add the `ingest` map to the data configuration
// NOTE: The first argument to the `.insert` function is an arbitrary string
//       given to identify the incoming data. It serves no other purpose.
dc0.insert("Everything", ingest)

bc0 = new BuildConfig()
bc0.nodetype = "linux"
bc0.name = "Install"
bc0.env_vars = ['PREFIX=/tmp/testbed',
                'PATH=/tmp/testbed/bin:$PATH']
bc0.build_cmds = ["make",
                  "make install PREFIX=$PREFIX"]

// Pass the data configuration into the build configuration object for processing
bc0.test_configs = [dc0]

bc0.test_cmds = ["make check",
                 "simple --help",
                 "simple --version"]

utils.run([bc0])
