node("linux") {
    stage("Checkout") {
        scm checkout
    }
    stage("Install") {
        env.PREFIX = "/opt/testbed"
        sh "make"
        sh "make install PREFIX=${env.PREFIX}"
    }
    stage("Test") {
        env.PATH = "${env.PREFIX}/bin:${env.PATH}"
        sh "make check"
        sh "simple --help"
        sh "simple --version"
    }
    stage("Artifactory") {
        def server = Artifactory.server 'bytesalad'
        def buildInfo = Artifactory.newBuildInfo()
        def uploadSpec = """{
          "files": [
            {
              "pattern": "test_results/**",
              "target": "generic-local/testbed/static/"
            }
         ]
        }"""
        server.upload spec: uploadSpec, buildInfo: buildInfo
        server.publishBuildInfo buildInfo
    }
}
